export const mockFHIS = {
  establishments: [
    {
      AddressLine1: "",
      AddressLine2: "1 & 30 Donald Dewar Court",
      AddressLine3: "Provost Fraser Drive",
      AddressLine4: "Aberdeen",
      BusinessName: "1 & 30 DONALD DEWAR COURT",
      BusinessType: "Caring Premises",
      BusinessTypeID: 5,
      ChangesByServerID: 0,
      Distance: null,
      FHRSID: 982849,
      LocalAuthorityBusinessID: "EHDC12463",
      LocalAuthorityCode: "760",
      LocalAuthorityEmailAddress: "commercial@aberdeencity.gov.uk",
      LocalAuthorityName: "Aberdeen City",
      LocalAuthorityWebSite: "http://www.aberdeencity.gov.uk",
      NewRatingPending: false,
      Phone: "",
      PostCode: "AB16 5JB",
      RatingDate: "2017-05-15T00:00:00",
      RatingKey: "fhis_pass_en-gb",
      RatingValue: "Pass",
      RightToReply: "",
      SchemeType: "FHIS",
      geocode: {
        longitude: "-2.16749501228333",
        latitude: "57.1613082885742",
      },
      scores: {
        Hygiene: null,
        Structural: null,
        ConfidenceInManagement: null,
      },
    },
    {
      AddressLine1: "",
      AddressLine2: "210 Market Street",
      AddressLine3: "Aberdeen",
      AddressLine4: "",
      BusinessName: "210 BISTRO",
      BusinessType: "Restaurant/Cafe/Canteen",
      BusinessTypeID: 1,
      ChangesByServerID: 0,
      Distance: null,
      FHRSID: 593681,
      LocalAuthorityBusinessID: "EHDC9793",
      LocalAuthorityCode: "760",
      LocalAuthorityEmailAddress: "commercial@aberdeencity.gov.uk",
      LocalAuthorityName: "Aberdeen City",
      LocalAuthorityWebSite: "http://www.aberdeencity.gov.uk",
      NewRatingPending: false,
      Phone: "",
      PostCode: "AB11 5PQ",
      RatingDate: "2019-02-13T00:00:00",
      RatingKey: "fhis_pass_en-gb",
      RatingValue: "Pass",
      RightToReply: "",
      SchemeType: "FHIS",
      geocode: {
        longitude: "-2.092258",
        latitude: "57.142278",
      },
      scores: {
        Hygiene: null,
        Structural: null,
        ConfidenceInManagement: null,
      },
    },
  ],
  meta: {
    dataSource: "Lucene",
    extractDate: "2024-02-28T23:41:34.0411565+00:00",
    itemCount: 2160,
    returncode: "OK",
    totalCount: 2160,
    totalPages: 1,
    pageSize: 5000,
    pageNumber: 1,
  },
  links: [
    {
      rel: "self",
      href: "http://api.ratings.food.gov.uk/establishments?localauthorityid=197",
    },
  ],
};

export const mockFHRC = {
  establishments: [
    {
      AddressLine1: "Dover",
      AddressLine2: "Kent",
      AddressLine3: "",
      AddressLine4: "",
      BusinessName: "12 High Street",
      BusinessType: "Takeaway/sandwich shop",
      BusinessTypeID: 7844,
      ChangesByServerID: 0,
      Distance: null,
      FHRSID: 1451705,
      LocalAuthorityBusinessID: "PI/000085288",
      LocalAuthorityCode: "182",
      LocalAuthorityEmailAddress: "publicprotection@dover.gov.uk",
      LocalAuthorityName: "Dover",
      LocalAuthorityWebSite: "http://www.dover.gov.uk/",
      NewRatingPending: false,
      Phone: "",
      PostCode: "CT16 1DR",
      RatingDate: "2022-07-19T00:00:00",
      RatingKey: "fhrs_5_en-gb",
      RatingValue: "5",
      RightToReply: "",
      SchemeType: "FHRS",
      geocode: {
        longitude: "1.308306",
        latitude: "51.128421",
      },
      scores: {
        Hygiene: 5,
        Structural: 5,
        ConfidenceInManagement: 5,
      },
    },
    {
      AddressLine1: "Dover",
      AddressLine2: "Kent",
      AddressLine3: "",
      AddressLine4: "",
      BusinessName: "31 Biggin Street",
      BusinessType: "Pub/bar/nightclub",
      BusinessTypeID: 7843,
      ChangesByServerID: 0,
      Distance: null,
      FHRSID: 1155580,
      LocalAuthorityBusinessID: "PI/000080610",
      LocalAuthorityCode: "182",
      LocalAuthorityEmailAddress: "publicprotection@dover.gov.uk",
      LocalAuthorityName: "Dover",
      LocalAuthorityWebSite: "http://www.dover.gov.uk/",
      NewRatingPending: false,
      Phone: "",
      PostCode: "CT16 1BU",
      RatingDate: "2019-06-28T00:00:00",
      RatingKey: "fhrs_5_en-gb",
      RatingValue: "5",
      RightToReply: "",
      SchemeType: "FHRS",
      geocode: {
        longitude: null,
        latitude: null,
      },
      scores: {
        Hygiene: 0,
        Structural: 0,
        ConfidenceInManagement: 5,
      },
    },
  ],
  meta: {
    dataSource: "Lucene",
    extractDate: "2024-02-29T00:49:09.8516059+00:00",
    itemCount: 2160,
    returncode: "OK",
    totalCount: 2160,
    totalPages: 1,
    pageSize: 5000,
    pageNumber: 1,
  },
  links: [
    {
      rel: "self",
      href: "http://api.ratings.food.gov.uk/establishments?localauthorityid=197",
    },
  ],
};
